#
###################################
# Site wide configuration
####################################
#
title: John Schrute
email: john.schrute@loremipsum.com
description: "My website description"
url: 'https://mukulkhanna.github.io/leonids-v2' # change this as per your website
keywords: [""]

#
###################################
# Jekyll configuration
####################################
#

# host: 0.0.0.0
# port: 4000

timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

collections:
  projects:
    output: true

plugins:
  - jekyll-gist
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: John Schrute
  avatar: profile_picture.jpeg
  job: "Employee of the year 2019"
  bio: "Assistant Regional Manager, Dunder Mifflin"
  github: username
  email: johnschrute@gmail.com
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  medium: username
  linkedin: username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
